// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyryp-5lvSe4GOvcJXWqr24Z5p2vHsfQY',
    appId: '1:516273499737:web:d7834596c8c12a0fab0b48',
    messagingSenderId: '516273499737',
    projectId: 'cheq-app-prod-a8e01',
    authDomain: 'cheq-app-prod-a8e01.firebaseapp.com',
    storageBucket: 'cheq-app-prod-a8e01.firebasestorage.app',
    measurementId: 'G-582LD8WV4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr6zt2-PedjguKxADC-oUD3pE-Mjj2sgo',
    appId: '1:516273499737:android:f9418f9f889071caab0b48',
    messagingSenderId: '516273499737',
    projectId: 'cheq-app-prod-a8e01',
    storageBucket: 'cheq-app-prod-a8e01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATApKkZaD64FYBZ4ncP2Rr1mRwPpcN1K4',
    appId: '1:516273499737:ios:5bd7c0766e1d66d6ab0b48',
    messagingSenderId: '516273499737',
    projectId: 'cheq-app-prod-a8e01',
    storageBucket: 'cheq-app-prod-a8e01.firebasestorage.app',
    androidClientId: '516273499737-lnkerp90tpcqaetb5mvjpf7fslnbj3ku.apps.googleusercontent.com',
    iosClientId: '516273499737-u0jatb93ukc7i659oa0qnvmbsin1lrag.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheq',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATApKkZaD64FYBZ4ncP2Rr1mRwPpcN1K4',
    appId: '1:516273499737:ios:5bd7c0766e1d66d6ab0b48',
    messagingSenderId: '516273499737',
    projectId: 'cheq-app-prod-a8e01',
    storageBucket: 'cheq-app-prod-a8e01.firebasestorage.app',
    androidClientId: '516273499737-lnkerp90tpcqaetb5mvjpf7fslnbj3ku.apps.googleusercontent.com',
    iosClientId: '516273499737-u0jatb93ukc7i659oa0qnvmbsin1lrag.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyryp-5lvSe4GOvcJXWqr24Z5p2vHsfQY',
    appId: '1:516273499737:web:dcc736db056b9c91ab0b48',
    messagingSenderId: '516273499737',
    projectId: 'cheq-app-prod-a8e01',
    authDomain: 'cheq-app-prod-a8e01.firebaseapp.com',
    storageBucket: 'cheq-app-prod-a8e01.firebasestorage.app',
    measurementId: 'G-6HF3Y7GLS1',
  );
}
