// lib/main.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'screens/auth_gate.dart';
import 'package:cheq/screens/daily_planner_screen.dart';
import 'package:cheq/providers/theme_provider.dart'; // 

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Future.wait([
      Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform),
      NotificationService.instance.initialize(),
    ]).timeout(const Duration(seconds: 6));
  } catch (e) {
    debugPrint("Core initialization exception or timeout caught: $e");
  }
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // await NotificationService.instance.initialize();
  runApp(const ProviderScope(child: CheqApp()));
}


// ── ROOT APPLICATION COMPONENT (Updated to ConsumerWidget) ──────────────────
class CheqApp extends ConsumerWidget {
  const CheqApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch the global theme state provider
    final themeMode = ref.watch(themeModeProvider);

    return MaterialApp(
      title: 'Cheq',
      debugShowCheckedModeBanner: false,
      
      // Pass the active theme state parameter here
      themeMode: themeMode, 
      
      // ☀️ Define your Light Theme Rules
      theme: ThemeData(
        colorSchemeSeed: Colors.teal,
        brightness: Brightness.light,
        useMaterial3: true,
      ),
      
      // 🌙 Define your Dark Theme Rules
      darkTheme: ThemeData(
        colorSchemeSeed: Colors.teal,
        brightness: Brightness.dark,
        useMaterial3: true,
      ),
      
      home: const AuthGate(),
    );
  }
}