// lib/main.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'screens/auth_gate.dart';
import 'package:cheq/screens/daily_planner_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    // 2. Run initializations concurrently with a global 6-second timeout curtain
    await Future.wait([
      Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform),
      NotificationService.instance.initialize(),
    ]).timeout(
      const Duration(seconds: 6),
      onTimeout: () {
        print("⚠️ Core services initialization took too long. Proceeding to UI...");
        return []; // Returns an empty list to satisfy Future.wait structure
      },
    );
  } catch (e) {
    print("❌ Critical Initialization Exception caught: $e");
  }
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // await NotificationService.instance.initialize();
  runApp(const ProviderScope(child: CheqApp()));
}


class CheqApp extends StatelessWidget {
  const CheqApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cheq',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Colors.teal,
        useMaterial3: true,
      ),
      home: const AuthGate(),
    );
  }
}