// lib/main.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'screens/auth_gate.dart';
import 'package:cheq/providers/theme_provider.dart'; 
import 'package:cheq/providers/custom_theme_provider.dart';
import '../services/notification_service.dart';
import 'package:shared_preferences/shared_preferences.dart';

final sharedPrefsProvider = Provider<SharedPreferences>((ref) => throw UnimplementedError());

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final prefs = await SharedPreferences.getInstance();
  try {
    await Future.wait([
      Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform),
      NotificationService.instance.initialize(),
    ]).timeout(const Duration(seconds: 2));
  } catch (e) {
    debugPrint("Core initialization exception or timeout caught: $e");
  }
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // await NotificationService.instance.initialize();
  runApp(
    ProviderScope(
      overrides: [sharedPrefsProvider.overrideWithValue(prefs),
      ],
      child: const CheqApp(),
    ),
  );
}


// ── ROOT APPLICATION COMPONENT (Updated to ConsumerWidget) ──────────────────
class CheqApp extends ConsumerWidget {
  const CheqApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watch the global theme state provider
    final themeMode = ref.watch(themeModeProvider);
    final currentAccent = ref.watch(customAccentProvider);

    return MaterialApp(
      title: 'moon',
      debugShowCheckedModeBanner: false,
      
      // Pass the active theme state parameter here
      themeMode: themeMode, 
      
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: currentAccent,
          brightness: Brightness.light,
        ),
      ),
      
      darkTheme: ThemeData(
        useMaterial3: true, 
        colorScheme: ColorScheme.fromSeed(
          seedColor: currentAccent,
          brightness: Brightness.dark,
        ),
      ),
      
      home: const AuthGate(),
    );
  }
}